about
RomanSoltan/team-project-12 pull request #12
Opened 2024-09-07 10:55 UTC by annakharytonova

2024-09-07 12:11 UTC, RomanSoltan requested changes
для початку

2024-09-07 12:11 UTC, RomanSoltan commented on src/partials/about.html
> +    <div class="about-div2">
назвіть клас about-img-box

2024-09-07 12:11 UTC, RomanSoltan commented on src/partials/about.html
> +    <div class="about-div1">
назвіть клас about-content

2024-09-07 12:11 UTC, RomanSoltan commented on src/partials/about.html
> +  <div class="container about-container">
структура має бути такою: 
div class=container
     div class=about-container
     div class=about-container
div class=container

2024-09-07 13:18 UTC, annakharytonova commented on src/partials/about.html
> +      <h2 class="about-title">About Us</h2>
+

2024-09-07 13:18 UTC, annakharytonova commented on src/partials/about.html
> +    <div class="about-div2">
+

2024-09-07 13:18 UTC, annakharytonova commented on src/partials/about.html
> +    <div class="about-div1">
+

2024-09-07 15:07 UTC, annakharytonova commented on src/partials/about.html
> +  <div class="container about-container">
виправила

2024-09-07 19:58 UTC, RomanSoltan requested changes
.about-text-block не потрібно задавати флекс. відстань між параграфами задати margin-bottom і обнулити крайню геометрію. кнопці задати мінімальну ширину.

2024-09-08 06:03 UTC, RomanSoltan requested changes
Виправте помилки в коді і видаліть зайві конструкції щоб не вибивало помилок

2024-09-08 06:48 UTC, RomanSoltan requested changes
Good job! This is the last edit I see

2024-09-08 06:48 UTC, RomanSoltan commented on src/partials/about.html
> +<section class="about-section" id="about-section">
Додайте до секції загальний клас .section для вертикальних відступів, які підтягнуться з base.css

2024-09-08 07:06 UTC, RomanSoltan requested changes
one more time

2024-09-08 07:06 UTC, RomanSoltan commented on src/partials/about.html
> +<section class="section" id="about-section">
У секції клас .sectіon залишіть і додайте ще один клас .about-section. має бути два класи

2024-09-08 07:20 UTC, RomanSoltan approved these changes
Good job

2024-09-08 07:20 UTC, merged