review
RomanSoltan/team-project-12 pull request #13
Opened 2024-09-07 13:28 UTC by MarynaOr

пробний пуш, в мене локально не працюють картинки, інше зроблено.

2024-09-07 16:29 UTC, RomanSoltan requested changes
Марина потрібно правильно прописати медіа-запити. Спочатку пишете стилі для мобілки, потім відкриваєте медіа запит для таба. після для деска. неправильно прописана структура

2024-09-07 18:32 UTC, MarynaOr commented
Прошу більш детально описати проблему, я перевірила і зробила код чистішим, і код відповідає всім правилам.

2024-09-07 19:29 UTC, RomanSoltan requested changes
У вас не співпадає ширина карток у десктопній версії має бути 370 а є 335. ширину задайте за допомогою calc((100% - 40px) / 3; Вона має автоматично вирахуватися і картки розтягнуться. Це для початку

2024-09-07 19:29 UTC, RomanSoltan commented on src/css/reviews.css
> +.reviews-title {
видалити стилі .reviews-title Вам підтягнуться стилі з загального класу .section-title, коли ви пропишете його в заголовку в html

2024-09-07 19:29 UTC, RomanSoltan commented on src/partials/reviews.html
> +    <h2 class="reviews-title">Reviews</h2>
змінити в заголовку клас .reviews-title на клас .section-title

2024-09-07 19:29 UTC, RomanSoltan commented on src/css/reviews.css
> +@media screen and (min-width: 768px) {
теж видалити медіа-запит

2024-09-08 10:57 UTC, RomanSoltan requested changes
1 відстань між картками 20px у desk, 16px tab, 0 mob .
2. .reviews-item-tab видалити width: 344px;
3. reviews-list забрати min-width: 370px
4. пересвідчитися на адаптивному екрані що картки розтягуться на всю ширину

2024-09-08 12:08 UTC, RomanSoltan approved these changes

2024-09-08 12:09 UTC, RomanSoltan commented
well done

2024-09-08 12:09 UTC, merged